force-app/main/default/objects/Bike__c/Bike__c.object-meta.xml
<CustomObject>
    <label>Bike</label>
    <nameField>
        <label>Bike_Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bikes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Controllers Apex/objects/CustomSettingObjects__c/CustomSettingObjects__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>AssignMentCustomSetting</label>
</CustomObject>

force-app/main/default/objects/CustomSettingObjects__c/fields/ActiveCustomSetting__c.field-meta.xml
<CustomField>
    <fullName>ActiveCustomSetting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ActiveCustomSetting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Custom Setting/HandlerForCustomSettingTrigger.cls
public class HandlerForCustomSettingTrigger {
    public static void checkforCustomSetting(List<Bike__c> bikeObjectList){
        
        for(Bike__c bikeObject:bikeObjectList){
            try{
                CustomSettingObjects__c custObject=[select Id, ActiveCustomSetting__c, CreatedById from CustomSettingObjects__c where CreatedById=:bikeObject.OwnerId];
            	if(custObject.ActiveCustomSetting__c!=true){
                	bikeObject.Id.addError('From Trigger Custom Setting Error');
            	}
            }
            catch(Exception ex){
                bikeObject.Id.addError('From Trigger Custom Setting Error');
            }
        }
    }
}