force-app/main/default/objects/Bike__c/Bike__c.object-meta.xml
<CustomObject>
    <label>Bike</label>
    <nameField>
        <label>Bike_Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bikes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Controllers Apex/objects/Bike__c/fields/bike_id__c.field-meta.xml
<CustomField>
    <fullName>bike_id__c</fullName>
    <description>bike number</description>
    <inlineHelpText>help text</inlineHelpText>
    <label>bike_id</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bike__c/fields/Bike_owner__c.field-meta.xml
<CustomField>
    <fullName>Bike_owner__c</fullName>
    <label>Bike_owner</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Trigger Apex/testCustomSettingTrigger.cls
@isTest
public class testCustomSettingTrigger {
	@isTest
    public static void testMethodForBike(){
        List<Bike__c> bikeList=new List<Bike__c>();
        //try{
            	Bike__c bikeObject=new Bike__c();
            	bikeObject.Name='Pulser 220';
            	bikeObject.bike_id__c=111;
                bikeObject.Bike_owner__c='shubham';
                bikeList.add(bikeObject);
        Database.insert(bikeList);
        //}
        //catch(DMLException ex){
           // System.assertEquals(true,ex.getMessage().contains('You can\'t have sufficient permissions'));
        //}
        
    }
}