force-app/main/default/objects/Job_Shubham__c/Job_Shubham__c.object-meta.xml
<CustomObject>
    <label>Job_Shubham</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Job_Shubham Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job_Shubhams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Controllers Apex/objects/Job_Shubham__c/fields/Expires_ON__c.field-meta.xml
<CustomField>
    <fullName>Expires_ON__c</fullName>
    <label>Expires ON</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Scheduled Apex/ExpireJobInactiveScheduler.cls
public class ExpireJobInactiveScheduler implements Schedulable {
    public static void execute(SchedulableContext sc){
        List<Job_Shubham__c> jobObjectList=[SELECT Expires_ON__c, Id, Name FROM Job_Shubham__c where Expires_ON__c < TODAY];
        List<Job_Shubham__c> jobListUpdate=new List<Job_Shubham__c>();
        for(Job_Shubham__c jobObject:jobObjectList){
            jobObject.Active__c=false;
            jobListUpdate.add(jobObject);
        }
        Database.update(jobListUpdate);
        
    }
}