force-app/main/default/objects/Job_Shubham__c/Job_Shubham__c.object-meta.xml
<CustomObject>
    <label>Job_Shubham</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Job_Shubham Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job_Shubhams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Shubham__c/fields/Hired_Applicants__c.field-meta.xml
<CustomField>
    <fullName>Hired_Applicants__c</fullName>
    <label>Hired Applicants</label>
    <summaryForeignKey>Candidate_Shubham__c.Job_Shubham__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/Controllers Apex/objects/Job_Shubham__c/fields/Total_position__c.field-meta.xml
<CustomField>
    <fullName>Total_position__c</fullName>
    <label>Total position</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Trigger Apex/HandlerForJobTrigger.cls
public class HandlerForJobTrigger {
    public static void forActiveStateOfJob(List<Job_Shubham__c> jobObjectList){
        for(Job_Shubham__c jobObject: jobObjectList){
            if(jobObject.Active__c==true){
                jobObject.Id.addError('This Job is active and cannot be deleted');
            }
        }
    }
    public static void activeTrueAfterUpdatePosition(List<Job_Shubham__c> jobObjectList){
        for(Job_Shubham__c jobObject:jobObjectList){
            if(jobObject.Total_position__c > jobObject.Hired_Applicants__c){
                jobObject.Active__c=true;
            }
        }
    } 
}