force-app/main/default/objects/Job_Shubham__c/Job_Shubham__c.object-meta.xml
<CustomObject>
    <label>Job_Shubham</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Job_Shubham Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job_Shubhams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Controllers Apex/objects/Job_Shubham__c/fields/Expires_ON__c.field-meta.xml
<CustomField>
    <fullName>Expires_ON__c</fullName>
    <label>Expires ON</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Controllers Apex/objects/Job_Shubham__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Shubham__c/fields/Qualification_required__c.field-meta.xml
<CustomField>
    <fullName>Qualification_required__c</fullName>
    <label>Qualification required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BBA</fullName>
            </value>
            <value>
                <fullName>BCom</fullName>
            </value>
            <value>
                <fullName>BSc</fullName>
            </value>
            <value>
                <fullName>BTech</fullName>
            </value>
            <value>
                <fullName>MBA</fullName>
            </value>
            <value>
                <fullName>MSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Shubham__c/fields/Skills_required__c.field-meta.xml
<CustomField>
    <fullName>Skills_required__c</fullName>
    <label>Skills required</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>.Net</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C++</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>Linux</fullName>
            </value>
            <value>
                <fullName>Networking</fullName>
            </value>
            <value>
                <fullName>People Skills</fullName>
            </value>
            <value>
                <fullName>PHP</fullName>
            </value>
            <value>
                <fullName>Self-Management</fullName>
            </value>
            <value>
                <fullName>team Player</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Controllers Apex/objects/Job_Shubham__c/fields/Total_position__c.field-meta.xml
<CustomField>
    <fullName>Total_position__c</fullName>
    <label>Total position</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Scheduled Apex/testExpireJobInactiveScheduler.cls
@isTest
public class testExpireJobInactiveScheduler {
	@isTest
    public static void testMethodForJobExpire(){
        List<Job_Shubham__c> jobObjectList=new List<Job_Shubham__c>();
        for(Integer itr=0; itr<20;itr++){
            Job_Shubham__c jobObject=new Job_Shubham__c();
        	jobObject.RecordTypeId='0122w000000SNg8AAG';
        	jobObject.Name__c='tester_jobs'+itr;
        	jobObject.Skills_required__c='C';
        	jobObject.Qualification_required__c='BTech';
       	 	Date mydate=date.newInstance(2023, 4, 4);
        	jobObject.Expires_ON__c=mydate;
        	jobObject.Total_position__c=5;
	        jobObject.Active__c=true;
            jobObjectList.add(jobObject);
        }
        Database.insert(jobObjectList);
        string schedule='0 0 0 17 4 ?';
        Test.startTest();
        ExpireJobInactiveScheduler expObject=new ExpireJobInactiveScheduler();
        System.schedule('Job Expire On Schedule', schedule, expObject);
        Test.stopTest();
        List<Job_Shubham__c> jobCheckObjectList=[select Id ,Expires_ON__c,Active__c from Job_Shubham__c where Name Like 'tester_jobs%'];
        System.debug(jobCheckObjectList);
        for(Job_Shubham__c jobCheck:jobCheckObjectList){
            System.assertEquals(false, jobCheck.Active__c);
        }
    }
}