force-app/main/default/classes/Controllers Apex/objects/Account/fields/active_contact_count__c.field-meta.xml
<CustomField>
    <fullName>active_contact_count__c</fullName>
    <label>active_contact_count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Harshya task/FutureMethodOfTask.cls
public with sharing class FutureMethodOfTask {
    @future
    public static void methodForAccount(Id id){
        Account accountObject=[SELECT Id,Name,active_contact_count__c from Account where Id=:id];
        Integer count=[SELECT COUNT() from contact Where AccountId=:accountObject.Id AND Active__c=true];
        accountObject.active_contact_count__c=count;
        update accountObject;
    }
}