force-app/main/default/objects/Book_Details__c/Book_Details__c.object-meta.xml
<CustomObject>
    <label>Book Details</label>
    <nameField>
        <label>Name Of Book</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Book Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Controllers Apex/objects/Book_Details__c/fields/After_Undelete__c.field-meta.xml
<CustomField>
    <fullName>After_Undelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Undelete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Trigger Apex/HandlerClassForBookDetails.cls
public class HandlerClassForBookDetails {
    public static void afterUndeleteChangeStatusMethod(List<Book_Details__c> bookListObject){
        List<Book_Details__c> bookObject=new List<Book_Details__c>();
         for(Book_Details__c c : bookListObject){
            Book_Details__c book1=new Book_Details__c();
            book1.Id=c.Id;
            book1.After_Undelete__c = true;
        	bookObject.add(book1);
   		}
        Database.update(bookObject);
    }
}