force-app/main/default/classes/Controllers Apex/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{0000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Controllers Apex/objects/Job_Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Controllers Apex/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Review resume</fullName>
            </value>
            <value>
                <fullName>Phone Screen</fullName>
            </value>
            <value>
                <fullName>Schedule interviews</fullName>
            </value>
            <value>
                <fullName>Extend an Offer</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Controllers Apex/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/Controllers Apex/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Position</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Open - Approved</fullName>
            </value>
            <value>
                <fullName>Closed - Filled</fullName>
            </value>
            <value>
                <fullName>Closed - Not Approved</fullName>
            </value>
            <value>
                <fullName>Closed - Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobAppliationTriggerHandler.cls
public class JobAppliationTriggerHandler {
    public static void beforeInsertStatusNewPosition(List<Job_Application__c> lstJobApplication){
        for(Job_Application__c jobObj:lstJobApplication){
            jobObj.Status__c='New';
        }
    }
    public static void afterPositionVancancyFull(List<Job_Application__c> lstJobApplication,Map<Id,Job_Application__c> oldJobApplications){
        Set<Id> postionsId =new set<Id>();
        postionsId.add(oldJobApplications.Values().Position__c);
        Map<Id,Position__c> mapPosition=new Map<Id,Position__c>([Select Id,Name,Number_Of_Vacancy__c  From Position__c Where Id IN:postionsId]);
        Map<Id,Job_Application__c> mapAllJobApplication=new Map<Id,Job_Application__c> ([Select Id,Name,Candidate__c,Position__c From Job_Application__c Where Position__c IN :postionsId AND Status__c = 'Hired']);
        for(Job_Application__c objJobApplication:lstJobApplication){
          if(objJobApplication.status__c != oldJobApplications.get(objJobApplication.Id).Status__c && objJobApplication.Status__c == 'Hired' && mapAllJobApplication.Size()==mapPosition.get(objJobApplication.Position__c).Number_Of_Vacancy__c ){  
            objJobApplication.Status__c.addError('Positions Vaccancies are Full');     
          }
        }
    }
}