force-app/main/default/classes/Controllers Apex/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Controllers Apex/objects/Candidate__c/fields/Candidate_Name__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Name__c</fullName>
    <formula>First_Name__c +&quot; &quot;+ Last_Name__c</formula>
    <label>Candidate Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Controllers Apex/objects/Candidate__c/fields/Confirm_Password__c.field-meta.xml
<CustomField>
    <fullName>Confirm_Password__c</fullName>
    <label>Confirm Password</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/Controllers Apex/objects/Candidate__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Controllers Apex/objects/Candidate__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{0000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Controllers Apex/objects/Job_Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Controllers Apex/objects/Job_Application__c/fields/Candidate_Name__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Name__c</fullName>
    <formula>Candidate__r.Candidate_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Candidate Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Controllers Apex/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/Controllers Apex/ControllerRecruitment.cls
public class ControllerRecruitment {
    static Integer otp=0;
    @AuraEnabled(cacheable=true)
    public static List<Candidate__c> usernamePasswordAuth(String usName,String pass){
        System.debug('usName'+usName+'  pass'+pass);
        List<Candidate__c> objCandidate = [Select Id,Password__c,Username__c,Candidate_Name__c from Candidate__c where Username__c=:usName AND Password__c=:pass];
        System.debug('objCandidate=:'+objCandidate);
        return objCandidate;
    }

    @AuraEnabled(cacheable=true)
    public static List<Position__c> allPositionRecruitment(String canId,Integer itr){
        List<Position__c> lstPosition=[SELECT Id, Name, (SELECT Candidate__c FROM Job_Applications__r) FROM Position__c WHERE Id IN (SELECT Position__c FROM Job_Application__c WHERE Candidate__c =:canId)];
        Map<String,Position__c> mapLst=new Map<String,Position__c>(); 
        set<String> positionName=new set<String> ();
        for(Position__c pObj:lstPosition){
            positionName.add(pObj.Name);
        }
        List<Position__c> objPosition=[SELECT Id, Name, Skills_Required__c,Close_Date__c, RecordTypeId FROM Position__c WHERE Name NOT IN : positionName];
        return objPosition;
    }

    @AuraEnabled(cacheable=true)
    public static List<Position__c> appliedPositionRecruitment(String canId,Integer itr){
        List<Position__c> lstPosition=[SELECT Id, Name, (SELECT Candidate__c FROM Job_Applications__r) FROM Position__c WHERE Id IN (SELECT Position__c FROM Job_Application__c WHERE Candidate__c =:canId)];
        Map<String,Position__c> mapLst=new Map<String,Position__c>(); 
        set<String> positionName=new set<String> ();
        for(Position__c pObj:lstPosition){
            positionName.add(pObj.Name);
        }
        List<Position__c> objPosition=[SELECT Id, Name, Skills_Required__c,Close_Date__c, RecordTypeId FROM Position__c WHERE Name IN : positionName];
        return objPosition;
    }

    @AuraEnabled
    public static Boolean jopApplication(String posId,String canId){
        Boolean flag=false;
        try{
            Job_Application__c objJob=new Job_Application__c(Candidate__c=canId,Position__c=posId);
            Database.insert(objJob);
            flag=true;
        }
        catch(Exception ex){
            flag=false;
        }
        return flag;
    }

    @AuraEnabled
    public static Integer optGenrator(){
        otp =Math.round((Math.random() * (900000) + 100000));
        return otp;
    }

    @AuraEnabled
    public static Boolean otpSendOnMail(String Email1,Integer OTPnew){
        Boolean flag=false;
        try{
            System.debug('OTPnew'+OTPnew+'  ..........');
            System.debug('Email1'+Email1);
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setToAddresses(new List<String>{ Email1 });
                mail.setSubject('One time password for Create new Password');
                mail.setPlainTextBody('One Time Pasword : '+OTPnew);
                //Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                Messaging.SingleEmailMessage[] messages =  new List<Messaging.SingleEmailMessage> {mail};
                Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
            flag=true;
        }
        catch(Exception ex){
            System.debug('Email Message :-'+ex.getMessage());
            flag=false;
        }
      return flag;  
    }

    @AuraEnabled(cacheable=true)
    public static List<Candidate__c> emailOfCandidate(String Email){
        System.debug('Email '+Email);
        List<Candidate__c> objCandidate = [Select Id,Password__c,Username__c,Candidate_Name__c,Email__c  from Candidate__c where Email__c =:Email];
        System.debug('objCandidate=:'+objCandidate);
        return objCandidate;
    }
    @AuraEnabled
    public static Boolean passwordChangeMethod(String Email,String passwordNew){
        Boolean flag=false;
        try {
            List<Candidate__c> objCandidate = [Select Id,Password__c, Confirm_Password__c,Username__c,Candidate_Name__c,Email__c  from Candidate__c where Email__c =:Email];
            List<Candidate__c> candiList=new List<Candidate__c>();

            for(Candidate__c can:objCandidate){
                can.Password__c=passwordNew;
                can.Confirm_Password__c=passwordNew;
                candiList.add(can);
            }
            Database.update(candiList,false);
            flag=true;
        } catch (Exception e) {
            
            flag=false;
        }
        return flag;
    }
}

//System.debug('OTP Is Genrate : - '+ControllerRecruitment.optGenrator());
//ControllerRecruitment.otpSendOnMail('savintambe@gmail.com',ControllerRecruitment.optGenrator());