force-app/main/default/objects/Candidate_Shubham__c/Candidate_Shubham__c.object-meta.xml
<CustomObject>
    <label>Candidate_Shubham</label>
    <nameField>
        <label>Candidate_Shubham Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate_Shubhams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Controllers Apex/objects/Candidate_Shubham__c/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <label>Application Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Candidate_Shubham__c/fields/Expected_Salary__c.field-meta.xml
<CustomField>
    <fullName>Expected_Salary__c</fullName>
    <label>Expected Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Controllers Apex/objects/Candidate_Shubham__c/fields/Job_Shubham__c.field-meta.xml
<CustomField>
    <fullName>Job_Shubham__c</fullName>
    <label>Job_Shubham</label>
    <referenceTo>Job_Shubham__c</referenceTo>
    <relationshipLabel>Candidate_Shubhams</relationshipLabel>
    <relationshipName>Candidate_Shubhams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Controllers Apex/objects/Candidate_Shubham__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>Last_Name__c  +  Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Shubham__c/Job_Shubham__c.object-meta.xml
<CustomObject>
    <label>Job_Shubham</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Job_Shubham Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job_Shubhams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Controllers Apex/objects/Job_Shubham__c/fields/Expires_ON__c.field-meta.xml
<CustomField>
    <fullName>Expires_ON__c</fullName>
    <label>Expires ON</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Controllers Apex/objects/Job_Shubham__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>contact1</relationshipLabel>
    <relationshipName>Job_Shubhams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Controllers Apex/objects/Job_Shubham__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Shubham__c/fields/Qualification_required__c.field-meta.xml
<CustomField>
    <fullName>Qualification_required__c</fullName>
    <label>Qualification required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BBA</fullName>
            </value>
            <value>
                <fullName>BCom</fullName>
            </value>
            <value>
                <fullName>BSc</fullName>
            </value>
            <value>
                <fullName>BTech</fullName>
            </value>
            <value>
                <fullName>MBA</fullName>
            </value>
            <value>
                <fullName>MSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Shubham__c/fields/Skills_required__c.field-meta.xml
<CustomField>
    <fullName>Skills_required__c</fullName>
    <label>Skills required</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>.Net</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C++</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>Linux</fullName>
            </value>
            <value>
                <fullName>Networking</fullName>
            </value>
            <value>
                <fullName>People Skills</fullName>
            </value>
            <value>
                <fullName>PHP</fullName>
            </value>
            <value>
                <fullName>Self-Management</fullName>
            </value>
            <value>
                <fullName>team Player</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Controllers Apex/objects/Job_Shubham__c/fields/Total_position__c.field-meta.xml
<CustomField>
    <fullName>Total_position__c</fullName>
    <label>Total position</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Shubham__c/recordTypes/Tester.recordType-meta.xml
<RecordType>
    <fullName>Tester</fullName>
    <active>false</active>
    <label>Tester</label>
</RecordType>

force-app/main/default/classes/Trigger Apex/testcandidateTriggerOfApplicant.cls
@isTest
public class testcandidateTriggerOfApplicant {
    @testSetup
    public static void testSteupCandidate(){
        Contact contactObject=new Contact();
        contactObject.LastName='Navale_test';
        contactObject.FirstName='Shubham_Test';
        contactObject.Email='shubham.navale8@gmail.com';
        insert contactObject;
        Contact contactObjectForjob=[select Id from Contact where LastName='Navale_test'];
        Job_Shubham__c jobObject=new Job_Shubham__c();
        jobObject.RecordTypeId='0122w000000SNg8AAG';
        jobObject.Name__c='tester jobs';
        jobObject.Skills_required__c='C';
        jobObject.Qualification_required__c='BTech';
        Date mydate=date.newInstance(2023, 6, 6);
        jobObject.Expires_ON__c=mydate;
        jobObject.Total_position__c=5;
        jobObject.Active__c=true;
        jobObject.Manager__c=contactObjectForjob.Id;
        Database.insert(jobObject,false);
        List<Candidate_Shubham__c> candidateObjectList=new List<Candidate_Shubham__c>();
        Job_Shubham__c idOfJobObject=[select Id from Job_Shubham__c];
        List<Candidate_Shubham__c> candiObject=new List<Candidate_Shubham__c>();
        
        for(Integer itrcandidate=0; itrcandidate<7; itrcandidate++){
            try{
            Candidate_Shubham__c candidateObject=new Candidate_Shubham__c();
            candidateObject.Job_Shubham__c=idOfJobObject.Id;
            candidateObject.Name='Empolyee_'+itrcandidate;
            candidateObject.First_Name__c='Shubham_Test_'+itrcandidate;
            candidateObject.Last_Name__c='Navale_Test_'+itrcandidate;
            candidateObject.Application_Date__c=date.newInstance(2023, 8, 4);
            candidateObject.Expected_Salary__c=60000;
            //candiObject.add(candidateObject);
            insert candidateObject;
            }
            catch(DmlException ex){
                System.debug('Job is now DeActive so error Occur : '+ex.getMessage());
            }
        }
    }
    
	@isTest
    public static void testcandidateNumberMatchApplicant(){
        Job_Shubham__c jobObject=[select Id, Active__c from Job_Shubham__c];
        List<Candidate_Shubham__c> canObject=[select Id , Job_Shubham__c, Name from Candidate_Shubham__c];
        System.debug('job id'+jobObject);
        System.debug('candidate := '+canObject);
        //System.assertEquals(false,jobObject.Active__c); 
        System.assertEquals(1, Limits.getEmailInvocations());
        System.assertNotEquals(0, Limits.getEmailInvocations());
        //System.assertEquals(true, HandlerForCandidateTrigger.candidateNumberMatchApplicant());
    }
}