force-app/main/default/objects/Candidate_Shubham__c/Candidate_Shubham__c.object-meta.xml
<CustomObject>
    <label>Candidate_Shubham</label>
    <nameField>
        <label>Candidate_Shubham Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate_Shubhams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Controllers Apex/objects/Candidate_Shubham__c/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <label>Application Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Controllers Apex/objects/Candidate_Shubham__c/fields/Job_Shubham__c.field-meta.xml
<CustomField>
    <fullName>Job_Shubham__c</fullName>
    <label>Job_Shubham</label>
    <referenceTo>Job_Shubham__c</referenceTo>
    <relationshipLabel>Candidate_Shubhams</relationshipLabel>
    <relationshipName>Candidate_Shubhams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Shubham__c/Job_Shubham__c.object-meta.xml
<CustomObject>
    <label>Job_Shubham</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Job_Shubham Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job_Shubhams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Other All Class/ForPracticeClassDemo.cls
public class ForPracticeClassDemo {
    public static void methodPractice(){
        //Job_Shubham__c jobObject=[select Id,CreatedDate,Name from Job_Shubham__c where Id='a042w00000yHyBYAA0'];
        // Candidate_Shubham__c candiObject=[SELECT Id, Name, First_Name__c, Last_Name__c, CreatedDate, Application_Date__c FROM Candidate_Shubham__c where Id='a052w00000ExQu8AAF'];
        // DateTime createdDateTime = candiObject.CreatedDate;
        // String createdDateString = createdDateTime.format('yyyy-MM-dd');
        // candiObject.Application_Date__c = Date.valueOf(createdDateString);
        // System.debug(candiObject.Application_Date__c);

    }
}